[package]
name = "expert-system"
version = "0.1.0"
edition = "2021"
authors = ["Gaspard Legendre <glegendr@student.42.fr>", "Lorenzo Jesu <lojesu@student.42.fr>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"